### PR TITLE
Add an error handling of event_text_changed()

### PR DESCRIPTION
**Pull request by sh8**
Fix this error by adding a None check for self._cur_handler.
https://github.com/numirias/semshi/issues/105

### CODE REVIEW

**Comment by alexcg1** [comment]
Is there any easy way to use your fork with Vim-Plug @sh8 ? Seems semshi hasn't had any updates for a long while so not expecting your PR to be merged any time soon

**Comment by blueyed** [comment]
Thanks for addressing this.

It should probably have a comment / updated doc there: currently it looks like the existing comment might refer to the newly added code.  Might make sense to turn it into a docstring, and then add a new comment with the new code.

**Comment by sh8** [comment]
> Is there any easy way to use your fork with Vim-Plug @sh8 ? Seems semshi hasn't had any updates for a long while so not expecting your PR to be merged any time soon

You can install the forked one like this;

```
Plug 'sh8/semshi', {'do': ':UpdateRemotePlugins'}
```

**Comment by sh8** [comment]
> Thanks for addressing this.
> 
> It should probably have a comment / updated doc there: currently it looks like the existing comment might refer to the newly added code. Might make sense to turn it into a docstring, and then add a new comment with the new code.

Thank you for pointing it out!

**Pull request merged**
